# Generated by Django 4.2.2 on 2023-06-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ClientName',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
