# Generated by Django 4.2.2 on 2023-06-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_clientname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='BillingMethod',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='Currency',
            field=models.CharField(max_length=100),
        ),
    ]
